// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "jbnvocx.h"

/////////////////////////////////////////////////////////////////////////////
// CJBNVOCX

IMPLEMENT_DYNCREATE(CJBNVOCX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CJBNVOCX properties

long CJBNVOCX::GetM_nWindowsMode()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CJBNVOCX::SetM_nWindowsMode(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CJBNVOCX operations

BOOL CJBNVOCX::OpenServer(LPCTSTR strIp, long nPort, LPCTSTR strUserName, LPCTSTR strPassword)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIp, nPort, strUserName, strPassword);
	return result;
}

BOOL CJBNVOCX::OpenChannel(long nChannel, long hVideoWnd)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nChannel, hVideoWnd);
	return result;
}

long CJBNVOCX::DefMessageProc(long wParam, long lParam)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		wParam, lParam);
	return result;
}

void CJBNVOCX::SendPTZCommand(long nPTZCommand, long nValue, long nChannelNo)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nPTZCommand, nValue, nChannelNo);
}

BOOL CJBNVOCX::ShowSetup(long bShow, long hServer, LPCTSTR csCapture)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bShow, hServer, csCapture);
	return result;
}

BOOL CJBNVOCX::VideoRecord(long nChannelNo, LPCTSTR szRootPath)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nChannelNo, szRootPath);
	return result;
}

BOOL CJBNVOCX::isConnect()
{
	BOOL result;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CJBNVOCX::Mute()
{
	BOOL result;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CJBNVOCX::SnapShot(long nChannelNo)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nChannelNo);
	return result;
}

BOOL CJBNVOCX::TalkBack()
{
	BOOL result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

long CJBNVOCX::GetChannelCount()
{
	long result;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CJBNVOCX::SetSelectChannel(long nChannelNo)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannelNo);
}

void CJBNVOCX::SetShowWindows(long nWindowsMode)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nWindowsMode);
}

void CJBNVOCX::CloseServer()
{
	InvokeHelper(0xf, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CJBNVOCX::CloseChannel(long nChannelNo)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannelNo);
}

void CJBNVOCX::SetControlLanguage(LPCTSTR strLanguage)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strLanguage);
}

long CJBNVOCX::GetSensorState(long nSensor)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nSensor);
	return result;
}

long CJBNVOCX::SetSensorState(long nSensor, long nState)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nSensor, nState);
	return result;
}

void CJBNVOCX::ShowSelectWnd(long bShowWnd)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bShowWnd);
}

long CJBNVOCX::GetSelectChannel()
{
	long result;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CJBNVOCX::OpenChannelEx(long nChannel, long hVideoWnd, long nStreamType, long bShowError)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nChannel, hVideoWnd, nStreamType, bShowError);
	return result;
}

void CJBNVOCX::PlayBack()
{
	InvokeHelper(0x17, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CJBNVOCX::SetScreenRatio(long nRatioType)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRatioType);
}

void CJBNVOCX::RealPlay()
{
	InvokeHelper(0x19, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CJBNVOCX::VideoRecordEx(long nChannel, LPCTSTR szRootPath, long bOn)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		nChannel, szRootPath, bOn);
	return result;
}

BOOL CJBNVOCX::OpenServerEx(LPCTSTR strServerIP, long nPort, LPCTSTR strUserName, LPCTSTR strPasswd, long nStreamType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strServerIP, nPort, strUserName, strPasswd, nStreamType);
	return result;
}

long CJBNVOCX::GetVersion()
{
	long result;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CJBNVOCX::ShowSetupEx(long bShow, long hServer, LPCTSTR csCapture, long nStreamType)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bShow, hServer, csCapture, nStreamType);
	return result;
}

long CJBNVOCX::ShowElectronicZoom(long nChannel)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nChannel);
	return result;
}

long CJBNVOCX::GetServerHandle()
{
	long result;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CJBNVOCX::ShowD2Para(long bShow)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bShow);
}

void CJBNVOCX::AttachServerHandle(long hServer, LPCTSTR ip, long port, LPCTSTR user, LPCTSTR psw)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4 VTS_BSTR VTS_BSTR;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hServer, ip, port, user, psw);
}

void CJBNVOCX::FullWindow()
{
	InvokeHelper(0x22, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CJBNVOCX::SetPTZSpeed(long nSpeed)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSpeed);
}

void CJBNVOCX::ShowPrePage()
{
	InvokeHelper(0x24, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CJBNVOCX::ShowNextPage()
{
	InvokeHelper(0x25, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CJBNVOCX::SetChlColor(long lColorType, long lColorValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lColorType, lColorValue);
}

void CJBNVOCX::CycleBrowse()
{
	InvokeHelper(0x27, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CJBNVOCX::StopCycleBrowse()
{
	InvokeHelper(0x28, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CJBNVOCX::SetServerOcxHandle(long hServer)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hServer);
}

void CJBNVOCX::SetOCXColorCase(long lColorCase)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lColorCase);
}

void CJBNVOCX::SetShowToScale(long nChannelNo, long bEnable)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannelNo, bEnable);
}

void CJBNVOCX::GetVideoSize(long lStreamType)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lStreamType);
}

void CJBNVOCX::SetPlayWnd(long bOriginalSize)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bOriginalSize);
}

CString CJBNVOCX::SnapShotEx(long nChannel, LPCTSTR strPath)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nChannel, strPath);
	return result;
}
