#if !defined(AFX_JBNVOCX_H__EE638D95_D829_4682_BDE4_08A27D99AACF__INCLUDED_)
#define AFX_JBNVOCX_H__EE638D95_D829_4682_BDE4_08A27D99AACF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CJBNVOCX wrapper class

class CJBNVOCX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CJBNVOCX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x97197a3a, 0x91e, 0x488d, { 0xb5, 0xba, 0x58, 0xea, 0xd9, 0x81, 0x9b, 0x4c } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetM_nWindowsMode();
	void SetM_nWindowsMode(long);

// Operations
public:
	BOOL OpenServer(LPCTSTR strIp, long nPort, LPCTSTR strUserName, LPCTSTR strPassword);
	BOOL OpenChannel(long nChannel, long hVideoWnd);
	long DefMessageProc(long wParam, long lParam);
	void SendPTZCommand(long nPTZCommand, long nValue, long nChannelNo);
	BOOL ShowSetup(long bShow, long hServer, LPCTSTR csCapture);
	BOOL VideoRecord(long nChannelNo, LPCTSTR szRootPath);
	BOOL isConnect();
	BOOL Mute();
	BOOL SnapShot(long nChannelNo);
	BOOL TalkBack();
	long GetChannelCount();
	void SetSelectChannel(long nChannelNo);
	void SetShowWindows(long nWindowsMode);
	void CloseServer();
	void CloseChannel(long nChannelNo);
	void SetControlLanguage(LPCTSTR strLanguage);
	long GetSensorState(long nSensor);
	long SetSensorState(long nSensor, long nState);
	void ShowSelectWnd(long bShowWnd);
	long GetSelectChannel();
	BOOL OpenChannelEx(long nChannel, long hVideoWnd, long nStreamType, long bShowError);
	void PlayBack();
	void SetScreenRatio(long nRatioType);
	void RealPlay();
	BOOL VideoRecordEx(long nChannel, LPCTSTR szRootPath, long bOn);
	BOOL OpenServerEx(LPCTSTR strServerIP, long nPort, LPCTSTR strUserName, LPCTSTR strPasswd, long nStreamType);
	long GetVersion();
	BOOL ShowSetupEx(long bShow, long hServer, LPCTSTR csCapture, long nStreamType);
	long ShowElectronicZoom(long nChannel);
	long GetServerHandle();
	void ShowD2Para(long bShow);
	void AttachServerHandle(long hServer, LPCTSTR ip, long port, LPCTSTR user, LPCTSTR psw);
	void FullWindow();
	void SetPTZSpeed(long nSpeed);
	void ShowPrePage();
	void ShowNextPage();
	void SetChlColor(long lColorType, long lColorValue);
	void CycleBrowse();
	void StopCycleBrowse();
	void SetServerOcxHandle(long hServer);
	void SetOCXColorCase(long lColorCase);
	void SetShowToScale(long nChannelNo, long bEnable);
	void GetVideoSize(long lStreamType);
	void SetPlayWnd(long bOriginalSize);
	CString SnapShotEx(long nChannel, LPCTSTR strPath);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_JBNVOCX_H__EE638D95_D829_4682_BDE4_08A27D99AACF__INCLUDED_)
