//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by JBSDKDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_JBSDKDEMO_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_OCX_TEST             130
#define IDD_DIALOG_LOGON                132
#define IDD_DIALOG_PLAYER_FILE          133
#define IDD_DIALOG_PLAYER_REMOTE        134
#define IDD_DIALOG_TALKBACK             135
#define IDD_DIALOG_BACK_CONNECT         136
#define IDD_DIALOG_AUDIO                137
#define IDD_DIALOG_FACE_MANAGE          138
#define IDD_DIALOG_IPC                  140
#define IDD_DIALOG_FACE_MODITY          141
#define IDC_BUTTON_CONNECT              1000
#define IDC_BUTTON_OPENCHANNEL          1001
#define IDC_BUTTON_CLOSECHANNEL         1002
#define IDC_BUTTON_CLOSECONNECT         1003
#define IDC_STATIC_IMAGE                1004
#define IDC_BUTTON_OPENFILE             1005
#define IDC_BUTTON_PAUSE                1006
#define IDC_BUTTON_STOP                 1007
#define IDC_BUTTON_BEGINTALK            1010
#define IDC_BUTTON_STOPTALK             1011
#define IDC_BUTTON_BEGIN_RECORD         1012
#define IDC_BUTTON_STOP_RECORD          1013
#define IDC_BUTTON_SETUP                1014
#define IDC_JBNVOCXCTRL1                1015
#define IDC_BUTTON_RELEASE              1016
#define IDC_STATIC_PLAY                 1017
#define IDC_BUTTON_OPENSERVER           1018
#define IDC_BUTTON_CLOSE_CHANNEL        1019
#define IDC_BUTTON_OCX_CHANNEL          1020
#define IDC_BUTTON_CLOSE_SERVER         1021
#define IDC_SLIDER_PLAYPOS              1022
#define IDC_STATIC_START_TIME           1023
#define IDC_EDIT_ADD                    1024
#define IDC_EDIT_PORT                   1025
#define IDC_EDIT_USERNAME               1026
#define IDC_EDIT_PASSWORD               1027
#define IDC_BUTTON_TEST                 1029
#define IDC_BUTTON_SNAPSHOT             1030
#define IDC_BUTTON_STEP_IN              1031
#define IDC_BUTTON_STEP_OUT             1032
#define IDC_BUTTON_PLAY                 1033
#define IDC_STATIC_TOTALTIME            1034
#define IDC_BUTTON_PLAYFAST             1035
#define IDC_BUTTON_FASTBACK             1036
#define IDC_BUTTON_PTZ_UP               1037
#define IDC_BUTTON_SEARCH_SERVER        1038
#define IDC_BUTTON_PTZ_DOWN             1039
#define IDC_BUTTON_LEFT                 1040
#define IDC_BUTTON_PTZ_RIGHT            1041
#define IDC_BUTTON_FOCUS_FAR            1042
#define IDC_BUTTON_FOCUS_NEAR           1043
#define IDC_COMBO_SERVER                1044
#define IDC_BUTTON_PTZ_STOP             1045
#define IDC_EDIT_CALL                   1046
#define IDC_BUTTON_CALL                 1047
#define IDC_BUTTON_SDK_SETUP            1048
#define IDC_STATIC_TALK                 1049
#define IDC_BUTTON_LOCAL_SNAPSHOT       1050
#define IDC_BUTTON_REMOTE_SNAPSHOT      1051
#define IDC_STATIC_CHANNEL              1052
#define IDC_CHECK_SENSOR_OUT1           1053
#define IDC_CHECK_SENSOR_OUT2           1054
#define IDC_BUTTON_ZOOM                 1055
#define IDC_STATIC_SECOND_IMAGE         1056
#define IDC_BUTTON_SECOND_WND           1057
#define IDC_SLIDER_BUFFER               1058
#define IDC_BUTTON_SWITCH               1059
#define IDC_STATIC_THREE_IMAGE          1060
#define IDC_STATIC_MIN_BUFFER           1061
#define IDC_BUTTON_GET_SERVER_STATE     1062
#define IDC_BUTTON_ATALKB               1063
#define IDC_BUTTON_CREATE_TM_SERVER     1065
#define IDC_EDIT_TM_PORT                1066
#define IDC_BUTTON_TM_INSERT_ITEM       1067
#define IDC_BUTTON_CAPTURE              1069
#define IDC_BUTTON_START                1071
#define IDC_BUTTON_END                  1072
#define IDC_BUTTON_OPENBC               1073
#define IDC_BUTTON_AUTO                 1074
#define IDC_BUTTON_SEARCH_FILE          1075
#define IDC_BUTTON_PLAY_FILE            1076
#define IDC_BT_PLAYBYTIME               1077
#define IDC_ET_CH                       1078
#define IDC_DTP_DATE_BEGIN              1081
#define IDC_DTP_TIME_BEGIN              1082
#define IDC_DTP_DATE_END                1083
#define IDC_DTP_TIME_END                1084
#define IDC_BUTTON_SHOW_PLAYPAGE        1086
#define IDC_JBNVOCX_CTRL                1087
#define IDC_EDIT_SERVER                 1088
#define IDC_BUTTON_OCX_TEST             1092
#define IDC_BUTTON_FILE_PLAYER          1093
#define IDC_BUTTON_FILE_PLAY            1094
#define IDC_BUTTON_REMOTE_PLAY_BY_TIME  1095
#define IDC_BUTTON_TALKBACK             1098
#define IDC_BUTTON_REMOTE_PLAYER        1099
#define IDC_BUTTON_BACK_CONNECT         1100
#define IDC_LIST_REPLAY_FILES           1101
#define IDC_BUTTON_SEARCH               1102
#define IDC_LIST_SERVER                 1103
#define IDC_STATIC_INFO                 1104
#define IDC_BUTTON_FLASH                1105
#define IDC_EDIT_OJTP2PId               1106
#define IDC_BUTTON_SET_P2PiD            1107
#define IDC_BUTTON_A_VOL                1108
#define IDC_SLIDER_ADC                  1109
#define IDC_SLIDER_DAC                  1110
#define IDC_SLIDER_GAIN                 1111
#define IDC_STATIC_ADC                  1113
#define IDC_STATIC_DAC                  1114
#define IDC_STATIC_GAIN                 1115
#define IDC_BUTTON_CHN9                 1116
#define IDC_BUTTON_FACE_LIB             1117
#define IDC_BUTTON_ADD                  1119
#define IDC_BUTTON_MODIFY               1120
#define IDC_BUTTON_DEL                  1121
#define IDC_LIST_FACE                   1122
#define IDC_COMBO_LIST                  1123
#define IDC_COMBO_PAGE                  1124
#define IDC_EDIT1                       1125
#define IDC_BUTTON_SERACH               1126
#define IDC_BUTTON_REMOTE_SELECT        1127
#define IDC_BUTTON_BATCH_INCREASE       1128
#define IDC_BUTTON_FACE_IMPORT          1129
#define IDC_BUTTON_FACE_EXPORT          1130
#define IDC_BUTTON_DELETE_ALL           1131
#define IDC_LIST_IPC                    1132
#define IDC_BUTTON_SELECT_PIC           1133
#define IDC_STATIC_NAME                 1135
#define IDC_STATIC_SEX                  1136
#define IDC_STATIC_AGE                  1137
#define IDC_EDIT2                       1138
#define IDC_EDIT_AGE                    1138
#define IDC_COMBO_SEX                   1139
#define IDC_EDIT3                       1141
#define IDC_EDIT_ID                     1141
#define IDC_EDIT4                       1142
#define IDC_EDIT_TEL                    1142
#define IDC_EDIT5                       1143
#define IDC_EDIT_ICCARD                 1143
#define IDC_EDIT6                       1144
#define IDC_EDIT_OTHER                  1144
#define IDC_EDIT7                       1145
#define IDC_EDIT_UUID                   1145
#define IDC_STATIC_PIC                  1147
#define IDC_STATIC_FACE                 1147
#define IDC_STATIC_SRC                  1148
#define IDC_EDIT_NAME                   1149
#define IDC_BUTTON_LISTEN               1150
#define IDC_BUTTON_OPEN_BACK_CONNECT    1153
#define IDC_COMBO_ROLE                  1153
#define IDC_BUTTON_DOWNLOAD_REC         1154
#define IDC_BUTTON_OPEN_CHANNEL         1155

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1156
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
